name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [x64, x86]

        include:
          - platform: x64
            arch: amd64
          - platform: x86
            arch: amd64_x86

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Env
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build
        run: msbuild -m /property:Configuration=Release /property:Platform=${{ matrix.platform }} console_events.sln

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: console_events.${{ matrix.platform }}
          path: bin/${{ matrix.platform }}/Release/console_events.exe
          compression-level: 9
          retention-days: 1

  create-release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip
        run: |
          zip -9 -j -D console_events.x64.${{ github.sha }}.zip artifacts/*x64/*
          zip -9 -j -D console_events.x86.${{ github.sha }}.zip artifacts/*x86/*

      - name: Release
        run: gh release create v1.0.${{github.run_number}} -t "v1.0.${{github.run_number}}" -n "Console Events v1.0.${{github.run_number}}" *.zip
        env:
          GH_TOKEN: ${{ github.token }}
